### ISSUE TITLE
Installation (vignette)

### ISSUE THREAD

**Issue by 0ruser** [jlaganie/BioenergyGHG#29]
J'aimerais insérer un lien a la vignette BioenergyGHG.html depuis la vignette Installation. Voici ce que j'ai fait dans le fichier .rmd:

The `BioenergyGHG` package is ready to go! We recomend you to follow the [BioenergyGHG](BioenergyGHG.html) vignette to learn about the overall concept of the package.

Ça fonctionne pour moi, mais pour un autre utilisateur qui a téléchargé le package, ça donne une erreur.

**Comment by Jean-Romain** [comment]
Il ne devrait y avoir aucun fichier `.html` dans le dossier `vignettes` (dans aucun dossier en fait). Que des fichiers `.Rmd`. Les vignettes sont construites au moment de l'installation et sont accessibles avec
 ```r
browseVignettes("BioenergyGHG")
````
