### ISSUE TITLE
Droits administratifs

### ISSUE THREAD

**Issue by 0ruser** [jlaganie/BioenergyGHG#31]
Je me demande si étant donné que c'est moi qui a les droits administratifs, tout changement que tu fais de ton côté dans le package requiert mon approbation avant qu'il soit valide pour l'utilisateur. Est-ce que c'est bien cela? Si mettons je part de ce monde tout d'un coup, est-ce que tu vas être en mesure de reprendre les droits?

Aussi, je veux ajouter Jérôme comme collaborateur pour qu'il puisse avoir accès au package. Peux-tu me rappeler comment faire, stp?

**Comment by 0ruser** [comment]
Salut Jean-Romain. 2 petites questions:
Je viens de changer le code pour installer le package:
Avant c'était ```devtools::install_github("0ruser/BioenergyGHG", dependencies=TRUE)```
Puis là j'ai changé par: ```devtools::install_github("jlaganie/BioenergyGHG", dependencies=TRUE)``` étant donné que c'est Jérôme l'administrateur. 
1- Jérôme a essayé de faire le changement lui-même, mais il n'est pas en mesure de 'commit' par contre moi j'ai pu faire le changement.
2- Lorsque j'installe avec ```devtools::install_github("0ruser/BioenergyGHG", dependencies=TRUE)``` ça fonctionne, mais ça devrait pas avec le changement.

**Comment by Jean-Romain** [comment]
Vous devriez éditer le README maintenant que c'est public

**Comment by jlaganie** [comment]
En fait tu le vois public maintenant car Fougère (qui remplace Rut) est en train d'installer le package mais normalement je le remet private quand il a fini..
